### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by wulfharth** [glat/MultiLinter#2]
I get the following output whenever it attempts to run. I've tried various values for the `Arguments` option (with quotes, without quotes, adding doubled backslashes after `{filePath}`, changing `"{filePath}"` to `.`), but nothing seems to make any difference. There are no weird characters or spaces in any file paths.

    Name = stylelint
    
                Enabled = true
             Executable = "stylelint.cmd"
              Arguments = ""{filePath}" -f json"
    AdditionalArguments = ""
       InstallationType = "local"
         FileExtensions = "scss"
            RuleHelpUrl = "https://stylelint.io/user-guide/rules/{ruleId}"
        ResultsSelector = "$[0].warnings"
         SourceSelector = ""
           LineSelector = "line"
         ColumnSelector = "column"
        EndLineSelector = ""
      EndColumnSelector = ""
        IsFatalSelector = ""
        MessageSelector = "text"
         RuleIdSelector = "rule"
    RuleHelpUrlSelector = ""
       SeveritySelector = "severity"
    
    Searching linters to be used for file extension ".scss"
    Linters found to be used for file extension ".scss" found: stylelint,
    Searching linter stylelint in local mode
    Searching linter stylelint in directory "C:\Path\To\Stylesheets"
    Illegal characters in path.
    
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2, String path3)
       at Glat.VSIX.MultiLinter.Helpers.LinterHelper.GetLinterPath(String linterName, LinterConfig linterConfig, String directoryPath) in C:\Users\giovanni\Source\Workspaces\glat\MultiLinter\Master\MultiLinter\Helpers\LinterHelper.cs:line 273
       at Glat.VSIX.MultiLinter.Helpers.LinterHelper.<>c__DisplayClass10_0.<RunAsync>b__0() in C:\Users\giovanni\Source\Workspaces\glat\MultiLinter\Master\MultiLinter\Helpers\LinterHelper.cs:line 313
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Glat.VSIX.MultiLinter.Linting.Linter.<AnalyzeAsync>d__5.MoveNext() in C:\Users\giovanni\Source\Workspaces\glat\MultiLinter\Master\MultiLinter\Linting\Linter.cs:line 57

**Comment by glat** [comment]
Do not set arguments. You should only set enabled to true and set comma separated extension list.
I think stylelint is not found because you did not have path for node.exe.
At setup time of node.js you should enable "ADD TO PATH".
